# Block Config file for Level add-on Version ${version}
# 
# This file lists the values for various blocks that are used to calculate the
# island level.
# 
# This section lists the limits for any particular block. Blocks over this amount
# are not counted.
# Format:
# MATERIAL: limit
limits:
  COBBLESTONE: 10000
  NETHERRACK: 1000
blocks:
  ACACIA_BUTTON: 1
  ACACIA_DOOR: 2
  ACACIA_FENCE: 2
  ACACIA_FENCE_GATE: 4
  ACACIA_LEAVES: 0
  ACACIA_LOG: 0
  ACACIA_PLANKS: 1
  ACACIA_PRESSURE_PLATE: 2
  ACACIA_SAPLING: 1
  ACACIA_SIGN: 6
  ACACIA_SLAB: 1
  ACACIA_STAIRS: 2
  ACACIA_TRAPDOOR: 3
  ACACIA_WALL_SIGN: 6
  ACACIA_WOOD: 1
  ACTIVATOR_RAIL: 1
  AIR: 0
  ALLIUM: 1
  ANCIENT_DEBRIS: 10
  ANDESITE: 1
  ANDESITE_SLAB: 1
  ANDESITE_STAIRS: 1
  ANDESITE_WALL: 1
  ANVIL: 10
  ATTACHED_MELON_STEM: 1
  ATTACHED_PUMPKIN_STEM: 1
  AZURE_BLUET: 1
  BAMBOO: 1
  BAMBOO_SAPLING: 1
  BARREL: 2
  BARRIER: 0
  BASALT: 1
  BEDROCK: 0
  BEETROOTS: 1
  BELL: 100
  BIRCH_BUTTON: 1
  BIRCH_DOOR: 2
  BIRCH_FENCE: 2
  BIRCH_FENCE_GATE: 4
  BIRCH_LEAVES: 0
  BIRCH_LOG: 0
  BIRCH_PLANKS: 1
  BIRCH_PRESSURE_PLATE: 2
  BIRCH_SAPLING: 1
  BIRCH_SIGN: 6
  BIRCH_SLAB: 1
  BIRCH_STAIRS: 2
  BIRCH_TRAPDOOR: 3
  BIRCH_WALL_SIGN: 6
  BIRCH_WOOD: 1
  BLACK_BANNER: 2
  BLACK_BED: 6
  BLACK_CARPET: 1
  BLACK_CONCRETE: 3
  BLACK_CONCRETE_POWDER: 2
  BLACK_GLAZED_TERRACOTTA: 5
  BLACK_SHULKER_BOX: 11
  BLACK_STAINED_GLASS: 2
  BLACK_STAINED_GLASS_PANE: 1
  BLACK_TERRACOTTA: 2
  BLACK_WALL_BANNER: 2
  BLACK_WOOL: 2
  BLACKSTONE: 1
  BLACKSTONE_SLAB: 1
  BLACKSTONE_STAIRS: 2
  BLACKSTONE_WALL: 1
  BLAST_FURNACE: 150
  BLUE_BANNER: 2
  BLUE_BED: 6
  BLUE_CARPET: 1
  BLUE_CONCRETE: 3
  BLUE_CONCRETE_POWDER: 2
  BLUE_GLAZED_TERRACOTTA: 5
  BLUE_ICE: 1
  BLUE_ORCHID: 1
  BLUE_SHULKER_BOX: 11
  BLUE_STAINED_GLASS: 2
  BLUE_STAINED_GLASS_PANE: 1
  BLUE_TERRACOTTA: 2
  BLUE_WALL_BANNER: 2
  BLUE_WOOL: 2
  BONE_BLOCK: 1
  BOOKSHELF: 5
  BRAIN_CORAL: 1
  BRAIN_CORAL_BLOCK: 1
  BRAIN_CORAL_FAN: 1
  BRAIN_CORAL_WALL_FAN: 1
  BREWING_STAND: 20
  BRICK_SLAB: 3
  BRICK_STAIRS: 5
  BRICK_WALL: 5
  BRICKS: 5
  BROWN_BANNER: 2
  BROWN_BED: 6
  BROWN_CARPET: 1
  BROWN_CONCRETE: 3
  BROWN_CONCRETE_POWDER: 2
  BROWN_GLAZED_TERRACOTTA: 5
  BROWN_MUSHROOM: 1
  BROWN_MUSHROOM_BLOCK: 1
  BROWN_SHULKER_BOX: 11
  BROWN_STAINED_GLASS: 2
  BROWN_STAINED_GLASS_PANE: 1
  BROWN_TERRACOTTA: 2
  BROWN_WALL_BANNER: 2
  BROWN_WOOL: 2
  BUBBLE_COLUMN: 1
  BUBBLE_CORAL: 1
  BUBBLE_CORAL_BLOCK: 1
  BUBBLE_CORAL_FAN: 1
  BUBBLE_CORAL_WALL_FAN: 1
  CACTUS: 1
  CAKE: 9
  CAMPFIRE: 5
  CARROTS: 1
  CARTOGRAPHY_TABLE: 6
  CARVED_PUMPKIN: 2
  CAULDRON: 10
  CAVE_AIR: 0
  CHAIN: 2
  CHAIN_COMMAND_BLOCK: 0
  CHEST: 8
  CHIPPED_ANVIL: 9
  CHISELED_NETHER_BRICKS: 2
  CHISELED_POLISHED_BLACKSTONE: 2
  CHISELED_QUARTZ_BLOCK: 2
  CHISELED_RED_SANDSTONE: 2
  CHISELED_SANDSTONE: 2
  CHISELED_STONE_BRICKS: 2
  CHORUS_FLOWER: 1
  CHORUS_PLANT: 1
  CLAY: 2
  COAL_BLOCK: 9
  COAL_ORE: 1
  COARSE_DIRT: 2
  COBBLESTONE: 1
  COBBLESTONE_SLAB: 1
  COBBLESTONE_STAIRS: 2
  COBBLESTONE_WALL: 1
  COBWEB: 10
  COCOA: 1
  COMMAND_BLOCK: 0
  COMPARATOR: 10
  COMPOSTER: 9
  CONDUIT: 1
  CORNFLOWER: 1
  CRACKED_NETHER_BRICKS: 1
  CRACKED_POLISHED_BLACKSTONE_BRICKS: 1
  CRACKED_STONE_BRICKS: 2
  CRAFTING_TABLE: 1
  CREEPER_HEAD: 1
  CREEPER_WALL_HEAD: 1
  CRIMSON_BUTTON: 1
  CRIMSON_DOOR: 2
  CRIMSON_FENCE: 2
  CRIMSON_FENCE_GATE: 4
  CRIMSON_FUNGUS: 1
  CRIMSON_HYPHAE: 1
  CRIMSON_NYLIUM: 1
  CRIMSON_PLANKS: 1
  CRIMSON_PRESSURE_PLATE: 2
  CRIMSON_ROOTS: 1
  CRIMSON_SIGN: 6
  CRIMSON_SLAB: 1
  CRIMSON_STAIRS: 2
  CRIMSON_STEM: 1
  CRIMSON_TRAPDOOR: 3
  CRIMSON_WALL_SIGN: 6
  CRYING_OBSIDIAN: 15
  CUT_RED_SANDSTONE: 1
  CUT_RED_SANDSTONE_SLAB: 1
  CUT_SANDSTONE: 1
  CUT_SANDSTONE_SLAB: 1
  CYAN_BANNER: 2
  CYAN_BED: 6
  CYAN_CARPET: 1
  CYAN_CONCRETE: 3
  CYAN_CONCRETE_POWDER: 2
  CYAN_GLAZED_TERRACOTTA: 5
  CYAN_SHULKER_BOX: 11
  CYAN_STAINED_GLASS: 2
  CYAN_STAINED_GLASS_PANE: 1
  CYAN_TERRACOTTA: 2
  CYAN_WALL_BANNER: 2
  CYAN_WOOL: 2
  DAMAGED_ANVIL: 5
  DANDELION: 1
  DARK_OAK_BUTTON: 1
  DARK_OAK_DOOR: 2
  DARK_OAK_FENCE: 2
  DARK_OAK_FENCE_GATE: 4
  DARK_OAK_LEAVES: 0
  DARK_OAK_LOG: 0
  DARK_OAK_PLANKS: 1
  DARK_OAK_PRESSURE_PLATE: 2
  DARK_OAK_SAPLING: 1
  DARK_OAK_SIGN: 6
  DARK_OAK_SLAB: 1
  DARK_OAK_STAIRS: 2
  DARK_OAK_TRAPDOOR: 3
  DARK_OAK_WALL_SIGN: 6
  DARK_OAK_WOOD: 1
  DARK_PRISMARINE: 1
  DARK_PRISMARINE_SLAB: 1
  DARK_PRISMARINE_STAIRS: 2
  DAYLIGHT_DETECTOR: 10
  DEAD_BRAIN_CORAL: 1
  DEAD_BRAIN_CORAL_BLOCK: 1
  DEAD_BRAIN_CORAL_FAN: 1
  DEAD_BRAIN_CORAL_WALL_FAN: 1
  DEAD_BUBBLE_CORAL: 1
  DEAD_BUBBLE_CORAL_BLOCK: 1
  DEAD_BUBBLE_CORAL_FAN: 1
  DEAD_BUBBLE_CORAL_WALL_FAN: 1
  DEAD_BUSH: 1
  DEAD_FIRE_CORAL: 1
  DEAD_FIRE_CORAL_BLOCK: 1
  DEAD_FIRE_CORAL_FAN: 1
  DEAD_FIRE_CORAL_WALL_FAN: 1
  DEAD_HORN_CORAL: 1
  DEAD_HORN_CORAL_BLOCK: 1
  DEAD_HORN_CORAL_FAN: 1
  DEAD_HORN_CORAL_WALL_FAN: 1
  DEAD_TUBE_CORAL: 1
  DEAD_TUBE_CORAL_BLOCK: 1
  DEAD_TUBE_CORAL_FAN: 1
  DEAD_TUBE_CORAL_WALL_FAN: 1
  DETECTOR_RAIL: 10
  DIAMOND_BLOCK: 300
  DIAMOND_ORE: 1
  DIORITE: 1
  DIORITE_SLAB: 1
  DIORITE_STAIRS: 1
  DIORITE_WALL: 1
  DIRT: 3
  DISPENSER: 5
  DRAGON_EGG: 150
  DRAGON_HEAD: 1
  DRAGON_WALL_HEAD: 1
  DRIED_KELP_BLOCK: 1
  DROPPER: 5
  EMERALD_BLOCK: 150
  EMERALD_ORE: 1
  ENCHANTING_TABLE: 150
  END_GATEWAY: 0
  END_PORTAL: 0
  END_PORTAL_FRAME: 0
  END_ROD: 1
  END_STONE: 1
  END_STONE_BRICK_SLAB: 2
  END_STONE_BRICK_STAIRS: 2
  END_STONE_BRICK_WALL: 2
  END_STONE_BRICKS: 2
  ENDER_CHEST: 150
  FARMLAND: 1
  FERN: 1
  FIRE: 0
  FIRE_CORAL: 1
  FIRE_CORAL_BLOCK: 1
  FIRE_CORAL_FAN: 1
  FIRE_CORAL_WALL_FAN: 1
  FLETCHING_TABLE: 8
  FLOWER_POT: 1
  FROSTED_ICE: 1
  FURNACE: 8
  GILDED_BLACKSTONE: 1
  GLASS: 2
  GLASS_PANE: 1
  GLOWSTONE: 1
  GOLD_BLOCK: 150
  GOLD_ORE: 1
  GRANITE: 1
  GRANITE_SLAB: 1
  GRANITE_STAIRS: 1
  GRANITE_WALL: 1
  GRASS: 4
  GRASS_BLOCK: 4
  GRASS_PATH: 4
  GRAVEL: 1
  GRAY_BANNER: 2
  GRAY_BED: 6
  GRAY_CARPET: 1
  GRAY_CONCRETE: 3
  GRAY_CONCRETE_POWDER: 2
  GRAY_GLAZED_TERRACOTTA: 5
  GRAY_SHULKER_BOX: 11
  GRAY_STAINED_GLASS: 2
  GRAY_STAINED_GLASS_PANE: 1
  GRAY_TERRACOTTA: 2
  GRAY_WALL_BANNER: 2
  GRAY_WOOL: 2
  GREEN_BANNER: 2
  GREEN_BED: 6
  GREEN_CARPET: 1
  GREEN_CONCRETE: 3
  GREEN_CONCRETE_POWDER: 2
  GREEN_GLAZED_TERRACOTTA: 5
  GREEN_SHULKER_BOX: 11
  GREEN_STAINED_GLASS: 2
  GREEN_STAINED_GLASS_PANE: 1
  GREEN_TERRACOTTA: 2
  GREEN_WALL_BANNER: 2
  GREEN_WOOL: 2
  GRINDSTONE: 8
  HAY_BLOCK: 2
  HEAVY_WEIGHTED_PRESSURE_PLATE: 2
  HONEY_BLOCK: 1
  HONEYCOMB_BLOCK: 1
  HOPPER: -10
  HORN_CORAL: 1
  HORN_CORAL_BLOCK: 1
  HORN_CORAL_FAN: 1
  HORN_CORAL_WALL_FAN: 1
  ICE: 5
  INFESTED_CHISELED_STONE_BRICKS: 2
  INFESTED_COBBLESTONE: 1
  INFESTED_CRACKED_STONE_BRICKS: 2
  INFESTED_MOSSY_STONE_BRICKS: 2
  INFESTED_STONE: 1
  INFESTED_STONE_BRICKS: 2
  IRON_BARS: 2
  IRON_BLOCK: 10
  IRON_DOOR: 5
  IRON_ORE: 1
  IRON_TRAPDOOR: 4
  JACK_O_LANTERN: 2
  JIGSAW: 1
  JUKEBOX: 10
  JUNGLE_BUTTON: 1
  JUNGLE_DOOR: 2
  JUNGLE_FENCE: 2
  JUNGLE_FENCE_GATE: 4
  JUNGLE_LEAVES: 0
  JUNGLE_LOG: 0
  JUNGLE_PLANKS: 1
  JUNGLE_PRESSURE_PLATE: 2
  JUNGLE_SAPLING: 1
  JUNGLE_SIGN: 6
  JUNGLE_SLAB: 1
  JUNGLE_STAIRS: 2
  JUNGLE_TRAPDOOR: 3
  JUNGLE_WALL_SIGN: 6
  JUNGLE_WOOD: 1
  KELP: 1
  KELP_PLANT: 1
  LADDER: 2
  LANTERN: 3
  LAPIS_BLOCK: 10
  LAPIS_ORE: 1
  LARGE_FERN: 1
  LAVA: 0
  LECTERN: 8
  LEVER: 1
  LIGHT_BLUE_BANNER: 2
  LIGHT_BLUE_BED: 6
  LIGHT_BLUE_CARPET: 1
  LIGHT_BLUE_CONCRETE: 3
  LIGHT_BLUE_CONCRETE_POWDER: 2
  LIGHT_BLUE_GLAZED_TERRACOTTA: 5
  LIGHT_BLUE_SHULKER_BOX: 11
  LIGHT_BLUE_STAINED_GLASS: 2
  LIGHT_BLUE_STAINED_GLASS_PANE: 1
  LIGHT_BLUE_TERRACOTTA: 2
  LIGHT_BLUE_WALL_BANNER: 2
  LIGHT_BLUE_WOOL: 2
  LIGHT_GRAY_BANNER: 2
  LIGHT_GRAY_BED: 6
  LIGHT_GRAY_CARPET: 1
  LIGHT_GRAY_CONCRETE: 3
  LIGHT_GRAY_CONCRETE_POWDER: 2
  LIGHT_GRAY_GLAZED_TERRACOTTA: 5
  LIGHT_GRAY_SHULKER_BOX: 11
  LIGHT_GRAY_STAINED_GLASS: 2
  LIGHT_GRAY_STAINED_GLASS_PANE: 1
  LIGHT_GRAY_TERRACOTTA: 2
  LIGHT_GRAY_WALL_BANNER: 2
  LIGHT_GRAY_WOOL: 2
  LIGHT_WEIGHTED_PRESSURE_PLATE: 3
  LILAC: 1
  LILY_OF_THE_VALLEY: 1
  LILY_PAD: 5
  LIME_BANNER: 2
  LIME_BED: 6
  LIME_CARPET: 1
  LIME_CONCRETE: 3
  LIME_CONCRETE_POWDER: 2
  LIME_GLAZED_TERRACOTTA: 5
  LIME_SHULKER_BOX: 11
  LIME_STAINED_GLASS: 2
  LIME_STAINED_GLASS_PANE: 1
  LIME_TERRACOTTA: 2
  LIME_WALL_BANNER: 2
  LIME_WOOL: 2
  LODESTONE: 10
  LOOM: 5
  MAGENTA_BANNER: 2
  MAGENTA_BED: 6
  MAGENTA_CARPET: 1
  MAGENTA_CONCRETE: 3
  MAGENTA_CONCRETE_POWDER: 2
  MAGENTA_GLAZED_TERRACOTTA: 5
  MAGENTA_SHULKER_BOX: 11
  MAGENTA_STAINED_GLASS: 2
  MAGENTA_STAINED_GLASS_PANE: 1
  MAGENTA_TERRACOTTA: 2
  MAGENTA_WALL_BANNER: 2
  MAGENTA_WOOL: 2
  MAGMA_BLOCK: 1
  MELON: 1
  MELON_STEM: 1
  MOSSY_COBBLESTONE: 1
  MOSSY_COBBLESTONE_SLAB: 1
  MOSSY_COBBLESTONE_STAIRS: 1
  MOSSY_COBBLESTONE_WALL: 1
  MOSSY_STONE_BRICK_SLAB: 2
  MOSSY_STONE_BRICK_STAIRS: 2
  MOSSY_STONE_BRICK_WALL: 2
  MOSSY_STONE_BRICKS: 2
  MOVING_PISTON: 1
  MUSHROOM_STEM: 1
  MYCELIUM: 5
  NETHER_BRICK_FENCE: 2
  NETHER_BRICK_SLAB: 1
  NETHER_BRICK_STAIRS: 2
  NETHER_BRICK_WALL: 2
  NETHER_BRICKS: 2
  NETHER_GOLD_ORE: 1
  NETHER_PORTAL: 1
  NETHER_QUARTZ_ORE: 1
  NETHER_SPROUTS: 1
  NETHER_WART: 1
  NETHER_WART_BLOCK: 2
  NETHERITE_BLOCK: 1
  NETHERRACK: 1
  NOTE_BLOCK: 10
  OAK_BUTTON: 1
  OAK_DOOR: 2
  OAK_FENCE: 2
  OAK_FENCE_GATE: 4
  OAK_LEAVES: 0
  OAK_LOG: 0
  OAK_PLANKS: 1
  OAK_PRESSURE_PLATE: 2
  OAK_SAPLING: 1
  OAK_SIGN: 6
  OAK_SLAB: 1
  OAK_STAIRS: 2
  OAK_TRAPDOOR: 3
  OAK_WALL_SIGN: 6
  OAK_WOOD: 1
  OBSERVER: 1
  OBSIDIAN: 10
  ORANGE_BANNER: 2
  ORANGE_BED: 6
  ORANGE_CARPET: 1
  ORANGE_CONCRETE: 3
  ORANGE_CONCRETE_POWDER: 2
  ORANGE_GLAZED_TERRACOTTA: 5
  ORANGE_SHULKER_BOX: 11
  ORANGE_STAINED_GLASS: 2
  ORANGE_STAINED_GLASS_PANE: 1
  ORANGE_TERRACOTTA: 2
  ORANGE_TULIP: 1
  ORANGE_WALL_BANNER: 2
  ORANGE_WOOL: 2
  OXEYE_DAISY: 1
  PACKED_ICE: 5
  PEONY: 1
  PETRIFIED_OAK_SLAB: 1
  PINK_BANNER: 2
  PINK_BED: 6
  PINK_CARPET: 1
  PINK_CONCRETE: 3
  PINK_CONCRETE_POWDER: 2
  PINK_GLAZED_TERRACOTTA: 5
  PINK_SHULKER_BOX: 11
  PINK_STAINED_GLASS: 2
  PINK_STAINED_GLASS_PANE: 1
  PINK_TERRACOTTA: 2
  PINK_TULIP: 1
  PINK_WALL_BANNER: 2
  PINK_WOOL: 2
  PISTON: 2
  PISTON_HEAD: 1
  PLAYER_HEAD: 1
  PLAYER_WALL_HEAD: 1
  PODZOL: 2
  POLISHED_ANDESITE: 1
  POLISHED_ANDESITE_SLAB: 1
  POLISHED_ANDESITE_STAIRS: 1
  POLISHED_BASALT: 1
  POLISHED_BLACKSTONE: 1
  POLISHED_BLACKSTONE_BRICK_SLAB: 2
  POLISHED_BLACKSTONE_BRICK_STAIRS: 2
  POLISHED_BLACKSTONE_BRICK_WALL: 2
  POLISHED_BLACKSTONE_BRICKS: 2
  POLISHED_BLACKSTONE_BUTTON: 1
  POLISHED_BLACKSTONE_PRESSURE_PLATE: 2
  POLISHED_BLACKSTONE_SLAB: 1
  POLISHED_BLACKSTONE_STAIRS: 2
  POLISHED_BLACKSTONE_WALL: 1
  POLISHED_DIORITE: 1
  POLISHED_DIORITE_SLAB: 1
  POLISHED_DIORITE_STAIRS: 1
  POLISHED_GRANITE: 1
  POLISHED_GRANITE_SLAB: 1
  POLISHED_GRANITE_STAIRS: 1
  POPPY: 1
  POTATOES: 1
  POTTED_ACACIA_SAPLING: 1
  POTTED_ALLIUM: 1
  POTTED_AZURE_BLUET: 1
  POTTED_BAMBOO: 1
  POTTED_BIRCH_SAPLING: 1
  POTTED_BLUE_ORCHID: 1
  POTTED_BROWN_MUSHROOM: 1
  POTTED_CACTUS: 1
  POTTED_CORNFLOWER: 1
  POTTED_CRIMSON_FUNGUS: 1
  POTTED_CRIMSON_ROOTS: 1
  POTTED_DANDELION: 1
  POTTED_DARK_OAK_SAPLING: 1
  POTTED_DEAD_BUSH: 1
  POTTED_FERN: 1
  POTTED_JUNGLE_SAPLING: 1
  POTTED_LILY_OF_THE_VALLEY: 1
  POTTED_OAK_SAPLING: 1
  POTTED_ORANGE_TULIP: 1
  POTTED_OXEYE_DAISY: 1
  POTTED_PINK_TULIP: 1
  POTTED_POPPY: 1
  POTTED_RED_MUSHROOM: 1
  POTTED_RED_TULIP: 1
  POTTED_SPRUCE_SAPLING: 1
  POTTED_WARPED_FUNGUS: 1
  POTTED_WARPED_ROOTS: 1
  POTTED_WHITE_TULIP: 1
  POTTED_WITHER_ROSE: 1
  POWERED_RAIL: 2
  PRISMARINE: 1
  PRISMARINE_BRICK_SLAB: 1
  PRISMARINE_BRICK_STAIRS: 2
  PRISMARINE_BRICKS: 2
  PRISMARINE_SLAB: 1
  PRISMARINE_STAIRS: 2
  PRISMARINE_WALL: 2
  PUMPKIN: 1
  PUMPKIN_STEM: 1
  PURPLE_BANNER: 2
  PURPLE_BED: 6
  PURPLE_CARPET: 1
  PURPLE_CONCRETE: 3
  PURPLE_CONCRETE_POWDER: 2
  PURPLE_GLAZED_TERRACOTTA: 5
  PURPLE_SHULKER_BOX: 11
  PURPLE_STAINED_GLASS: 2
  PURPLE_STAINED_GLASS_PANE: 1
  PURPLE_TERRACOTTA: 2
  PURPLE_WALL_BANNER: 2
  PURPLE_WOOL: 2
  PURPUR_BLOCK: 1
  PURPUR_PILLAR: 1
  PURPUR_SLAB: 1
  PURPUR_STAIRS: 2
  QUARTZ_BLOCK: 1
  QUARTZ_BRICKS: 2
  QUARTZ_PILLAR: 1
  QUARTZ_SLAB: 1
  QUARTZ_STAIRS: 2
  RAIL: 1
  RED_BANNER: 2
  RED_BED: 6
  RED_CARPET: 1
  RED_CONCRETE: 3
  RED_CONCRETE_POWDER: 2
  RED_GLAZED_TERRACOTTA: 5
  RED_MUSHROOM: 1
  RED_MUSHROOM_BLOCK: 1
  RED_NETHER_BRICK_SLAB: 2
  RED_NETHER_BRICK_STAIRS: 2
  RED_NETHER_BRICK_WALL: 2
  RED_NETHER_BRICKS: 2
  RED_SAND: 1
  RED_SANDSTONE: 1
  RED_SANDSTONE_SLAB: 1
  RED_SANDSTONE_STAIRS: 2
  RED_SANDSTONE_WALL: 2
  RED_SHULKER_BOX: 11
  RED_STAINED_GLASS: 2
  RED_STAINED_GLASS_PANE: 1
  RED_TERRACOTTA: 2
  RED_TULIP: 1
  RED_WALL_BANNER: 2
  RED_WOOL: 2
  REDSTONE_BLOCK: 10
  REDSTONE_LAMP: 10
  REDSTONE_ORE: 1
  REDSTONE_TORCH: 5
  REDSTONE_WALL_TORCH: 5
  REDSTONE_WIRE: 1
  REPEATER: 6
  REPEATING_COMMAND_BLOCK: 0
  RESPAWN_ANCHOR: 100
  ROSE_BUSH: 1
  SAND: 1
  SANDSTONE: 1
  SANDSTONE_SLAB: 1
  SANDSTONE_STAIRS: 2
  SANDSTONE_WALL: 2
  SCAFFOLDING: 1
  SEA_LANTERN: 9
  SEA_PICKLE: 1
  SEAGRASS: 1
  SHROOMLIGHT: 1
  SHULKER_BOX: 10
  SKELETON_SKULL: 10
  SKELETON_WALL_SKULL: 100
  SLIME_BLOCK: 10
  SMITHING_TABLE: 6
  SMOKER: 10
  SMOOTH_QUARTZ: 1
  SMOOTH_QUARTZ_SLAB: 1
  SMOOTH_QUARTZ_STAIRS: 1
  SMOOTH_RED_SANDSTONE: 1
  SMOOTH_RED_SANDSTONE_SLAB: 1
  SMOOTH_RED_SANDSTONE_STAIRS: 1
  SMOOTH_SANDSTONE: 1
  SMOOTH_SANDSTONE_SLAB: 1
  SMOOTH_SANDSTONE_STAIRS: 1
  SMOOTH_STONE: 1
  SMOOTH_STONE_SLAB: 1
  SNOW: 1
  SNOW_BLOCK: 1
  SOUL_CAMPFIRE: 1
  SOUL_FIRE: 1
  SOUL_LANTERN: 1
  SOUL_SAND: 2
  SOUL_SOIL: 1
  SOUL_TORCH: 1
  SOUL_WALL_TORCH: 1
  SPAWNER: 1
  SPONGE: 10
  SPRUCE_BUTTON: 1
  SPRUCE_DOOR: 2
  SPRUCE_FENCE: 2
  SPRUCE_FENCE_GATE: 4
  SPRUCE_LEAVES: 0
  SPRUCE_LOG: 0
  SPRUCE_PLANKS: 1
  SPRUCE_PRESSURE_PLATE: 2
  SPRUCE_SAPLING: 1
  SPRUCE_SIGN: 6
  SPRUCE_SLAB: 1
  SPRUCE_STAIRS: 2
  SPRUCE_TRAPDOOR: 3
  SPRUCE_WALL_SIGN: 6
  SPRUCE_WOOD: 1
  STICKY_PISTON: 1
  STONE: 1
  STONE_BRICK_SLAB: 1
  STONE_BRICK_STAIRS: 2
  STONE_BRICK_WALL: 2
  STONE_BRICKS: 2
  STONE_BUTTON: 1
  STONE_PRESSURE_PLATE: 2
  STONE_SLAB: 1
  STONE_STAIRS: 1
  STONECUTTER: 4
  STRIPPED_ACACIA_LOG: 0
  STRIPPED_ACACIA_WOOD: 1
  STRIPPED_BIRCH_LOG: 0
  STRIPPED_BIRCH_WOOD: 1
  STRIPPED_CRIMSON_HYPHAE: 1
  STRIPPED_CRIMSON_STEM: 1
  STRIPPED_DARK_OAK_LOG: 0
  STRIPPED_DARK_OAK_WOOD: 1
  STRIPPED_JUNGLE_LOG: 0
  STRIPPED_JUNGLE_WOOD: 1
  STRIPPED_OAK_LOG: 0
  STRIPPED_OAK_WOOD: 1
  STRIPPED_SPRUCE_LOG: 0
  STRIPPED_SPRUCE_WOOD: 1
  STRIPPED_WARPED_HYPHAE: 1
  STRIPPED_WARPED_STEM: 1
  STRUCTURE_BLOCK: 0
  STRUCTURE_VOID: 0
  SUGAR_CANE: 1
  SUNFLOWER: 1
  SWEET_BERRY_BUSH: 1
  TALL_GRASS: 1
  TALL_SEAGRASS: 1
  TARGET: 5
  TERRACOTTA: 2
  TNT: 5
  TORCH: 1
  TRAPPED_CHEST: 10
  TRIPWIRE: 2
  TRIPWIRE_HOOK: 2
  TUBE_CORAL: 1
  TUBE_CORAL_BLOCK: 1
  TUBE_CORAL_FAN: 1
  TUBE_CORAL_WALL_FAN: 1
  TURTLE_EGG: 1
  TWISTING_VINES: 1
  TWISTING_VINES_PLANT: 1
  VINE: 1
  VOID_AIR: 0
  WALL_TORCH: 1
  WARPED_BUTTON: 1
  WARPED_DOOR: 3
  WARPED_FENCE: 2
  WARPED_FENCE_GATE: 4
  WARPED_FUNGUS: 1
  WARPED_HYPHAE: 1
  WARPED_NYLIUM: 1
  WARPED_PLANKS: 1
  WARPED_PRESSURE_PLATE: 2
  WARPED_ROOTS: 1
  WARPED_SIGN: 6
  WARPED_SLAB: 1
  WARPED_STAIRS: 2
  WARPED_STEM: 1
  WARPED_TRAPDOOR: 3
  WARPED_WALL_SIGN: 6
  WARPED_WART_BLOCK: 1
  WATER: 0
  WEEPING_VINES: 1
  WEEPING_VINES_PLANT: 1
  WET_SPONGE: 10
  WHEAT: 1
  WHITE_BANNER: 2
  WHITE_BED: 6
  WHITE_CARPET: 1
  WHITE_CONCRETE: 3
  WHITE_CONCRETE_POWDER: 2
  WHITE_GLAZED_TERRACOTTA: 5
  WHITE_SHULKER_BOX: 11
  WHITE_STAINED_GLASS: 2
  WHITE_STAINED_GLASS_PANE: 1
  WHITE_TERRACOTTA: 2
  WHITE_TULIP: 1
  WHITE_WALL_BANNER: 2
  WHITE_WOOL: 2
  WITHER_ROSE: 1
  WITHER_SKELETON_SKULL: 10
  WITHER_SKELETON_WALL_SKULL: 10
  YELLOW_BANNER: 2
  YELLOW_BED: 6
  YELLOW_CARPET: 1
  YELLOW_CONCRETE: 3
  YELLOW_CONCRETE_POWDER: 2
  YELLOW_GLAZED_TERRACOTTA: 5
  YELLOW_SHULKER_BOX: 11
  YELLOW_STAINED_GLASS: 2
  YELLOW_STAINED_GLASS_PANE: 1
  YELLOW_TERRACOTTA: 2
  YELLOW_WALL_BANNER: 2
  YELLOW_WOOL: 2
  ZOMBIE_HEAD: 1
  ZOMBIE_WALL_HEAD: 1
worlds:
  caveblock-world:
    STONE: 0
    GRANITE: 0
    ANDESITE: 0
    DIORITE: 0
  acidisland_world:
    SAND: 0
    SANDSTONE: 0
    ICE: 0
